# deploy/docker-compose.yml

version: '3.8'

services:
    laravel:
        restart: unless-stopped
        container_name: livebook
        build:
            context: ../
            dockerfile: ./deploy/Dockerfile
        # При необходимости выделите столько томов, сколько нужно.
        volumes:
            - ../:/var/www/html/
        environment:
            APP_NAME: ${APP_NAME}
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            APP_KEY: ${APP_KEY}
            APP_VERSION: ${APP_VERSION}
            APP_URL: ${APP_URL}
            DB_CONNECTION: mysql
            DB_HOST: database
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            MAIL_MAILER: ${MAIL_MAILER}
            MAIL_HOST: ${MAIL_HOST}
            MAIL_PORT: ${MAIL_PORT}
            MAIL_USERNAME: ${MAIL_USERNAME}
            MAIL_PASSWORD: ${MAIL_PASSWORD}
            MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
            MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
            MAIL_FROM_NAME: ${MAIL_FROM_NAME}
        ports:
            - "8080:80"
        networks:
            - n-laravel
        depends_on:
            - database

    database:
        image: postgres
        restart: unless-stopped
        volumes:
            - postgresql:data/postgres
        # set shared memory limit when using docker-compose
        shm_size: 128mb
        # or set shared memory limit when deploy via swarm stack
        #volumes:
        #  - type: tmpfs
        #    target: /dev/shm
        #    tmpfs:
        #      size: 134217728 # 128*2^20 bytes = 128Mb
        environment:
            POSTGRES_DATABASE: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        networks:
            - n-laravel

    adminer:
        image: adminer
        restart: always
        ports:
            - "3306:3306"
volumes:
    v-database:


networks:
    n-laravel:
        driver: bridge
